In [2]:
import numpy as np

In [2]:
numeros=np.arange(11)**2

In [3]:
array([0,1,2,3,4,5,6,7,8,9,19,99])

NameError: name 'array' is not defined

In [4]:
indices[2,5,7]

NameError: name 'indices' is not defined

In [5]:
numeros[indices]

NameError: name 'indices' is not defined

In [6]:
numeros = np.arange(11)**2


In [7]:
numeros

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [8]:
indices = [2,5,7]

In [9]:
numeros[indices]

array([ 4, 25, 49], dtype=int32)

In [10]:
array([ 4, 25, 49], dtype=int32)

NameError: name 'array' is not defined

In [11]:

arreglo_frutas = np.array([
    ['Piña','Manzana','Pera','Melon'],
    ['Pera','Uva','Naranja','Papaya'],
    ['Frutilla','Platano','Granadilla','Sandia']
])

In [12]:

arreglo_frutas.shape

(3, 4)

In [13]:
arreglo_filas = np.array([
    [0,0],
    [1,1],
    [2,2],
])

In [14]:
arreglo_columnas = np.array([
    [1,3],
    [1,2],
    [0,2],
])

In [15]:
arreglo_frutas[arreglo_filas,arreglo_columnas]

array([['Manzana', 'Melon'],
       ['Uva', 'Naranja'],
       ['Frutilla', 'Granadilla']], dtype='<U10')

In [16]:
arreglo_frutas

array([['Piña', 'Manzana', 'Pera', 'Melon'],
       ['Pera', 'Uva', 'Naranja', 'Papaya'],
       ['Frutilla', 'Platano', 'Granadilla', 'Sandia']], dtype='<U10')

In [17]:
arreglo_filas = np.array([
    [0,0],
    [1,1],
    [2,2],
])

In [18]:
arreglo_frutatest = np.array([
    ['Piña','Manzana','Pera','Melon'],
    ['Pera','Uva','Naranja','Papaya'],
    ['Frutilla','Platano','Granadilla','Sandia'],
    ['uvas','verde','lima','limon']
])

SyntaxError: invalid syntax (<ipython-input-18-8f800c03441a>, line 1)

In [19]:
arreglo_frutatest = np.array([
    ['Piña','Manzana','Pera','Melon'],
    ['Pera','Uva','Naranja','Papaya'],
    ['Frutilla','Platano','Granadilla','Sandia'],
    ['uvas','verde','lima','limon']
])

In [20]:
arreglo_frutas.shape


(3, 4)

In [21]:
arreglo_frutatest.shape




(4, 4)

In [28]:
arreglo_frutatest = np.array([
   [ ['Piña','Manzana','Pera'],
    ['Pera','Uva','Naranja'],
    ['Frutilla','Platano','Granadilla'],
    ['uvas','verde','lima']],
    
    [ ['ajo','toronjil','lima'],
    ['achiote','lili','Naranjilla'],
    ['Frutillina','Platano amarillo','Granadillin'],
    ['reolin','verde','rarara']]
])

In [26]:
arreglo_frutatest.shape

(2, 4, 3)

In [34]:
arreglo_fila = np.array([
    [[0,0],
    [1,1],
    [2,2],
     [7,7]
    ],
    
    [[4,4],
    [5,5],
    [6,6],
    [8,8]]
])

In [35]:
arreglo_columna = np.array([
   [ [1,3],
    [1,3],
    [1,3],
    [1,3],
   ],
    
    
    [ [1,3],
    [1,3],
    [1,3],
    [1,3],
   ]
])

In [36]:
arreglo_frutatest[arreglo_fila,arreglo_columna]


IndexError: arrays used as indices must be of integer (or boolean) type

In [38]:
arreglo_frutacondicion = np.array([
    ['Piña','Manzana','Pera'],
    ['Pera','Uva','Naranja'],
    ['Frutilla','Platano','Granadilla'],
    ['uvas','verde','lima']])

In [39]:
nombre='Piña'

In [41]:
if nombre in arreglo_frutacondicion:
  print("esta")

esta


In [42]:
np.where(arreglo_frutacondicion == 'P')

(array([], dtype=int64), array([], dtype=int64))

In [46]:
arreglo_frutacondicion.index("P")

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [1]:
arreglo_frutas_3d = np.array([[['Piña','Manzana'],
                                ['Pera','Melon'],
                                ['Ciruela','Uva'],
                                ['Orito','Mandarina']],
                              
                               [['Naranja','Papaya'],
                                ['Frutilla','Platano'],
                                ['Granadilla','Sandia'],
                                ['Cacao','Mango']],
                              
                               [['Limon','Coco'],
                                ['Kiwi','Durazno'],
                                ['Almendra','Higo'],
                                ['Cereza','Guaba']]
])

NameError: name 'np' is not defined

In [3]:
arreglo_frutas_3d = np.array([[['Piña','Manzana'],
                                ['Pera','Melon'],
                                ['Ciruela','Uva'],
                                ['Orito','Mandarina']],
                              
                               [['Naranja','Papaya'],
                                ['Frutilla','Platano'],
                                ['Granadilla','Sandia'],
                                ['Cacao','Mango']],
                              
                               [['Limon','Coco'],
                                ['Kiwi','Durazno'],
                                ['Almendra','Higo'],
                                ['Cereza','Guaba']]
])

In [10]:
arreglo_frutas_3d.shape

(3, 4, 2)

In [5]:
arreglo_primera_dimension = np.array([
    [0,0],[0,0],[0,0],[0,0],
    [1,1],[1,1],[1,1],[1,1],
    [2,2],[2,2],[2,2],[2,2],
])

In [6]:

arreglo_segunda_dimension = np.array([
    [0,0],[1,1],[2,2],[3,3],
    [0,0],[1,1],[2,2],[3,3],
    [0,0],[1,1],[2,2],[3,3],
])

In [7]:
arreglo_tercera_dimension = np.array([
    [0,1],[0,1],[0,1],[0,1],
    [0,1],[0,1],[0,1],[0,1],
    [0,1],[0,1],[0,1],[0,1],
])

In [8]:
arreglo_frutas_3d

array([[['Piña', 'Manzana'],
        ['Pera', 'Melon'],
        ['Ciruela', 'Uva'],
        ['Orito', 'Mandarina']],

       [['Naranja', 'Papaya'],
        ['Frutilla', 'Platano'],
        ['Granadilla', 'Sandia'],
        ['Cacao', 'Mango']],

       [['Limon', 'Coco'],
        ['Kiwi', 'Durazno'],
        ['Almendra', 'Higo'],
        ['Cereza', 'Guaba']]], dtype='<U10')

In [11]:
arreglo_frutas_3d[arreglo_primera_dimension,arreglo_segunda_dimension,arreglo_tercera_dimension]


array([['Piña', 'Manzana'],
       ['Pera', 'Melon'],
       ['Ciruela', 'Uva'],
       ['Orito', 'Mandarina'],
       ['Naranja', 'Papaya'],
       ['Frutilla', 'Platano'],
       ['Granadilla', 'Sandia'],
       ['Cacao', 'Mango'],
       ['Limon', 'Coco'],
       ['Kiwi', 'Durazno'],
       ['Almendra', 'Higo'],
       ['Cereza', 'Guaba']], dtype='<U10')

In [12]:
arreglo_frutas_3d.flatten()

array(['Piña', 'Manzana', 'Pera', 'Melon', 'Ciruela', 'Uva', 'Orito',
       'Mandarina', 'Naranja', 'Papaya', 'Frutilla', 'Platano',
       'Granadilla', 'Sandia', 'Cacao', 'Mango', 'Limon', 'Coco', 'Kiwi',
       'Durazno', 'Almendra', 'Higo', 'Cereza', 'Guaba'], dtype='<U10')

In [13]:
palabras_con_P = np.array([fruta.startswith('P') for fruta in arreglo_frutas_3d.flatten()])

In [14]:
arreglo_frutas_3d.flatten()[palabras_con_P]

array(['Piña', 'Pera', 'Papaya', 'Platano'], dtype='<U10')

In [15]:
# Otro metodo
print(arreglo_frutas_3d[np.where(arreglo_frutas_3d.astype('<U1') == 'P')])

['Piña' 'Pera' 'Papaya' 'Platano']


In [ ]:
np.where()