In [1]:
import numpy as np
A = np.random.rand(1000, 1000, 3, 3)
identity = np.identity(3, dtype=A.dtype)
Ainv = np.zeros_like(A)
Atrans = np.zeros_like(A)
for i in range(1000):
    for j in range(1000):
        Ainv[i, j] = np.linalg.solve(A[i, j], identity)
        Atrans[i, j] = np.transpose(A[i, j])

In [2]:
import numpy as np

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
array([1, 2, 3])

NameError: name 'array' is not defined

In [5]:
 np.arange(5)

array([0, 1, 2, 3, 4])

In [6]:
 array([0, 1, 2, 3, 4])

NameError: name 'array' is not defined

In [7]:
 np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.linspace(0.0, 1.0, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

NameError: name 'array' is not defined

In [10]:
A = np.matrix([[2, 3],[1, -2]])
b = np.matrix([[8],[-10]])

In [11]:
x = (A**-1)*b

In [ ]:
a = np.array([[1, 0,4,7,9], [2, -1,9,4,3], [1, -1,4,8,3], [2, -2,8,9,9], [3, -7,0,3,3]])


In [ ]:
x.shape