In [1]:
import numpy as np

In [2]:
a = np.array([[1, 0,4,7,9], [2, -1,9,4,3], [1, -1,4,8,3], [2, -2,8,9,9], [3, -7,0,3,3]])

In [3]:
a.shape

(5, 5)

In [4]:
np.linalg.norm(a)

25.67099530598687

In [5]:
np.linalg.norm(a, np.inf)

30.0

In [6]:
np.linalg.norm(a, 1)

31.0

In [7]:
np.linalg.cond(a)

78.41315790123807

In [8]:
np.linalg.cond(a, np.inf)

173.7874659400545

In [9]:
np.trace(a)

16

In [10]:
np.einsum('ii', a)  # Traza

16

In [11]:
np.diag(a)

array([ 1, -1,  4,  9,  3])

In [12]:
np.einsum('ii -> i', a)  # Diagonal

array([ 1, -1,  4,  9,  3])

In [13]:
np.dot(a, a)

array([[ 46, -81,  76, 129, 111],
       [ 26, -37,  67, 127,  87],
       [ 28, -40,  75, 116,  99],
       [ 51, -87,  94, 178, 144],
       [  4, -20, -27,  29,  42]])

In [14]:
np.einsum('ij, jk', a, a)  # Producto matricial

array([[ 46, -81,  76, 129, 111],
       [ 26, -37,  67, 127,  87],
       [ 28, -40,  75, 116,  99],
       [ 51, -87,  94, 178, 144],
       [  4, -20, -27,  29,  42]])

In [24]:
u = np.ones([5], dtype = int)

In [26]:
u

array([1, 1, 1, 1, 1])

In [25]:
np.dot(a, u)

array([21, 17, 15, 26,  2])

In [27]:
np.einsum('ij, j', a, u)  # Matriz por vector


array([21, 17, 15, 26,  2])

In [28]:
np.dot(u, u)

5

In [29]:
np.einsum('i, i', u, u)  # Producto escalar por sí mismo

5

In [30]:
np.outer(u, u)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
np.einsum('i, j', u, u)  # Producto exterior

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
n